name: Run Batch Script

on:
  workflow_dispatch: # Aktiviert den Button für den rein manuellen Start im GitHub-Dashboard

jobs:
  run-batch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
          npm install @electric-sql/pglite
          
    - name: Run script and dump output
      run: |
        node batch.js

    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: script-output-log
        path: output.log
        retention-days: 7
